# -*- coding: utf-8 -*-
"""MLEx12d.ANN_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GEpxqzyV_DSlsS3a-WfiX89ORRmayA4O

# Machine Learning Exercise

# 12d. ANN for regression
"""

import numpy as np
import tensorflow as tf

"""# Generate Data"""

def f(x): # true function
  return x**3 - 2*x**2 + 3*x + 1

def f1(x): # true derivative
  return 3*x**2 - 4*x + 3

n = 200 # number of data points

x = np.linspace(-2.5, 2.5, n) # generate input samples

y = f(x) + np.random.normal(scale=2, size=n)  # noisy output

"""## Plot data"""

import matplotlib
from matplotlib import pyplot as plt

matplotlib.rcParams['figure.figsize'] = [9,6]

plt.plot(x, y, '.', label='Data')
plt.plot(x, f(x), label='True fn')
plt.legend()

"""## Model"""

model = tf.keras.Sequential([
    tf.keras.layers.Lambda(lambda x: tf.stack([x, x**2, x**3], axis=1)),
    tf.keras.layers.Dense(units=1, kernel_initializer=tf.random.normal)])

model.compile(
    loss=tf.keras.losses.MSE,
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
    metrics=['MSE', 'MAE', 'MAPE'])

"""# Train model"""

history = model.fit(x, y,
                    epochs=100,
                    batch_size=32,
                    verbose=1)

print(f"Final loss: {history.history['loss'][-1]}")

"""# Plot trained model"""

plt.plot(x, y, '.', label='Data')
plt.plot(x, f(x), label='True fn')
plt.plot(x, model(x), label='Predicted fn')
plt.legend()

"""# Derivative"""

def model_deriv(x):
  x = tf.Variable(x, dtype=tf.float32) # Convert x to a TensorFlow tensor
  with tf.GradientTape() as tape:
    y = model(x)
  return tape.gradient(y, x).numpy()

t = tf.constant([0.1, 0.4, 0.7], dtype=tf.float32)

print(f1(t))
print(model_deriv(t))

plt.plot(x, f1(x), label='True derivative')
plt.plot(x, model_deriv(x), label='Predicted derivative')
plt.legend()