# -*- coding: utf-8 -*-
"""MLEx9b.UserDefinedKernels

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGhBylZyLYkcVRcV2QI1KCKl4IdmHIZ3

# Machine Learning Exercise
# 9b. User defined Kernel Methods

##Import

Import libraries that contains the implementations of the functions used in the rest of the program.
"""

import math
import numpy as np
from sklearn import svm

print("Libraries imported.")

"""# Data set




"""

X = np.array( [ 'b', 'c', 'bc', 'cc', # 2^0 (0 occurrences of 'a')
      'a', 'ab', 'ca', 'bacb', 'ba', 'cab', # 2^1 (1 occurrences of 'a')
      'caba', 'abca', 'bbcaa', 'abccab', 'ccaabb', 'abba', 'baba', # 2^2 (2 occurrences of 'a')
      'aabba', 'aaa', 'babaa', 'abaca', 'baaac', 'acbaa', 'cabaab', # 2^3 (3 occurrences of 'a')
      'abcaaca', 'bcaaaca', 'abcbabacca', 'baccaaba', 'aabcaa', 'baacaa', # 2^4 (4 occurrences of 'a')
      'aabbaacc', 'abcacaba' ] )

t = np.array( [ 1, 1, 1, 1,
      2, 2, 2, 2, 2, 2,
      4, 4, 4, 4, 4, 4, 4,
      8, 8, 8, 8, 8, 8, 8,
      16, 16, 16, 16, 16, 16, 16, 16 ] )

test = np.array( ['bb', 'abc', 'ccaba', 'aabacb', 'bacabaca'] )
N = len(X)
#X = X.reshape((N,1))
print("Input shape: %r" %X.shape)
print("Output shape: %r" %t.shape)

"""# User-defined Kernel function

Let's define a kernel function (similarity function) based on the number of occurences of 'a' in the input string. Note: this kernel function does not directly implement a mapping from the input to the output.

"""

def count(w,ch):
  v = [ c for c in w if c==ch ]
  return len(v)


def k(u,v):
  d = abs(count(u,'a') - count(v,'a'))
  #return 1.0/(d+1)**2
  return math.exp(-d)

def my_kernel(U, V):
  N = len(U)
  M = len(V)
  K = np.empty((N,M))
  for i in range(0,N):
    for j in range(0,M):
      K[i][j] = k(U[i],V[j])
  return K


# Compute and print the Gram matrix (just for visualization purposes)
# not needed for training and testing

K = my_kernel(X,X)

# print the Gram matrix
for i in range(0,N):
  for j in range(0,N):
    print("%.3f" %K[i][j], end=' ')
  print('')

"""Fit classifier"""

# Train the model
classifier = svm.SVC(kernel=my_kernel)
classifier.fit(X,t)
# Compute the score (accuracy) on training set
classifier.score(X,t)

# Make predictions using the testing set
y_pred = classifier.predict(test)
print(y_pred)

"""# Regression model


"""

# Train the model
regressor = svm.SVR(kernel=my_kernel)
regressor.fit(X, t)
# Compute the score (R2) on training set
regressor.score(X,t)

# Make predictions using the testing set
y_pred = regressor.predict(test)
print(y_pred)

"""# Home Exercises

**Question 1**

Repeat the experiment with a noisy dataset and measure sensitivity of the method with respect to percentage on noisy samples.

**Question 2**

Define a kernel function for the SPAM classification problem (Exercise 3) and solve it with SVM. Compare the results with the ones obtained in Exercise 3.


"""